spring.application.name=demo
server.port=8080

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/todo_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123456

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Turn off H2 Console
spring.h2.console.enabled=false

# Logging
logging.level.web=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.com.example.demo=DEBUG

# External API Config
external.api.base-url=https://jsonplaceholder.typicode.com